# GitHub Sponsors
github: [FG98F]

# Patreon
patreon: 

# Open Collective
open_collective: 

# Ko-fi
ko_fi: 

# Tidelift
tidelift: 

# Community Bridge
community_bridge: 

# Liberapay
liberapay: 

# IssueHunt
issuehunt: 

# Otechie
otechie: 

# Custom (PayPal, etc)
custom: ['https://paypal.me/fg98f']